{{- if and .Values.global.enabled_aws_upbound .Values.controllerConfig.enabled }}
{{- with .Values.controllerConfig }}
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: {{ .metadata.name }}
  {{- if or $.Values.global.iam_role_arn_aws_upbound .metadata.iam_role_arn .metadata.annotations }}
  annotations:
    {{- if or $.Values.global.iam_role_arn_aws_upbound .metadata.iam_role_arn }}
    eks.amazonaws.com/role-arn: {{ default $.Values.global.iam_role_arn_aws_upbound .metadata.role_arn }}
    {{- end }}
    {{- range $key, $value := .metadata.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- if .metadata.labels }}
  labels:
    {{- range $key, $value := .metadata.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- .spec | toYaml | nindent 2 }}
{{- end }}
{{- end }}
