apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-aws-cloudwatch-metrics
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:  # from /charts/
              - addonChart: aws-cloudwatch-metrics
          - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      name: 'addon-{{name}}-{{addonChart}}'
    spec:
      project: default
      source:
        helm:
          releaseName: "{{addonChart}}"
          valueFiles:
          - '../../clusters/{{name}}/addons-values.yaml'
          values: |
            aws-cloudwatch-metrics:
              clusterName: {{metadata.annotations.cluster_name}}
              serviceAccount:
                name: {{metadata.annotations.aws_cloudwatch_metrics_sa}}
                annotations:
                  eks.amazonaws.com/role-arn: {{metadata.annotations.aws_cloudwatch_metrics_iam_role_arn}}
        repoURL: 'https://github.com/csantanapr/control-plane-eks'
        path: charts/{{addonChart}}
        targetRevision: HEAD
      destination:
        namespace: '{{metadata.annotations.aws_cloudwatch_namespace}}'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.
