apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-aws
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:  # from /charts/
              - addonChart: cluster-autoscaler
                addonNamespace: kube-system
              - addonChart: aws-cloudwatch-metrics
                addonNamespace: amazon-cloudwatch
              - addonChart: cert-manager
                addonNamespace: cert-manager
              - addonChart: external-secrets
                addonNamespace: external-secrets
          - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      name: 'addon-{{name}}-{{addonChart}}'
    spec:
      project: default
      source:
        helm:
          releaseName: "{{addonChart}}"
          valueFiles:
          - '../../clusters/{{name}}/addons-values.yaml'
          values: |
            aws-cloudwatch-metrics:
              clusterName: {{metadata.annotations.cluster_name}}
              serviceAccount:
                name: {{metadata.annotations.aws_cloudwatch_metrics_sa}}
                annotations:
                  eks.amazonaws.com/role-arn: {{metadata.annotations.aws_cloudwatch_metrics_iam_role_arn}}
            cert-manager:
              serviceAccount:
                annotations:
                  eks.amazonaws.com/role-arn: {{metadata.annotations.cert_manager_iam_role_arn}}
            cluster-autoscaler:
              image:
                tag: {{metadata.annotations.cluster_autoscaler_image_tag}}
              awsRegion: {{metadata.annotations.region}}
              autoDiscovery:
                clusterName: {{metadata.annotations.cluster_name}}
              rbac:
                serviceAccount:
                  name: {{metadata.annotations.cluster_autoscaler_sa}}
                  annotations:
                    eks.amazonaws.com/role-arn: {{metadata.annotations.cluster_autoscaler_iam_role_arn}}
        repoURL: 'https://github.com/csantanapr/control-plane-eks'
        path: charts/{{addonChart}}
        targetRevision: HEAD
      destination:
        namespace: '{{addonNamespace}}'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.