apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-test-appset
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:  # from /charts/
              - addonChart: test-appset
          - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      name: 'addon-{{name}}-{{addonChart}}'
    spec:
      project: default
      source:
        helm:
          releaseName: "{{addonChart}}"
          valueFiles:
          - '../../clusters/{{name}}/addons-values.yaml'
          values: |
            test-appset:
              serviceAccount:
                annotations:
                  eks.amazonaws.com/role-arn: {{metadata.annotations.cluster_name}}
        repoURL: 'https://github.com/csantanapr/gitops-control-plane'
        path: charts/{{addonChart}}
        targetRevision: HEAD
      destination:
        namespace: '{{addonChart}}'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.
