# external-secrets: {}
# kyverno: {}
# cluster-autoscaler: {}
# cert-manager: {}
# aws-cloudwatch-metrics: {}
# argo-cd: {}
# aws-privateca-issuer: {}
# external-dns: {}
# aws-load-balancer-controller: {}

