apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-cert-manager
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:  # from /charts/
              - addonChart: cert-manager # This is not really need it unless we can make this work below {{metadata.annotations.{{addonChart}}_iam_role_arn}}
          - clusters:
              selector:
                matchExpressions:
                - {key: 'akuity.io/argo-cd-cluster-name', operator: NotIn, values: [in-cluster]}
  template:
    metadata:
      name: 'addon-{{name}}-{{addonChart}}'
    spec:
      project: default
      source:
        helm:
          valueFiles:
          - '../../clusters/{{name}}/addons-values.yaml'
          values: |
            cert-manager:
              serviceAccount:
                annotations:
                  eks.amazonaws.com/role-arn: {{metadata.annotations.cert_manager_iam_role_arn}}
        repoURL: 'https://github.com/csantanapr/control-plane-eks'
        path: charts/{{addonChart}}
        targetRevision: HEAD
      destination:
        namespace: '{{metadata.annotations.cert_manager_namespace}}' # Hardcoding for now, we need this value from terraform in the cluster secret
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.