apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:  # from /charts/
              - addonChart: argo-cd
                addonNamespace: argocd
          - clusters:
              selector:
                matchLabels:
                  enable_argocd: "true"

  template:
    metadata:
      name: 'addon-{{name}}-{{addonNamespace}}'
    spec:
      project: default
      source:
        helm:
          releaseName: '{{addonChart}}'
          valueFiles:
          - '../../clusters/{{name}}/addons-values.yaml'
        repoURL: 'https://github.com/csantanapr/control-plane-eks'
        path: charts/{{addonChart}}
        targetRevision: HEAD
      destination:
        namespace: '{{addonNamespace}}'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.