apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusters
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: 'cluster-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/csantanapr/control-plane-eks
        targetRevision: HEAD
        path: 'clusters/{{name}}'
        directory:
          recurse: true
      destination:
        name: '{{name}}'
        namespace: '*'
      syncPolicy:
        automated: {}
